from enum import Enum


class NetworkMessage(Enum):
    Accept = 'ac'
    AdminInfo = 'ai'
    Alive = 'al'
    AddPlayer = 'ap'
    AutoPilot = 'au'
    CaptureFlag = 'cf'
    CustomSound = 'cs'
    CacheURL = 'cu'
    DropFlag = 'df'
    Enter = 'en'
    Exit = 'ex'
    FlagType = 'ft'
    FlagUpdate = 'fu'
    FetchResources = 'fr'
    GrabFlag = 'gf'
    GMUpdate = 'gm'
    GetWorld = 'gw'
    GameSettings = 'gs'
    GameTime = 'gt'
    Handicap = 'hc'
    Killed = 'kl'
    LagState = 'ls'
    Message = 'mg'
    NearFlag = 'Nf'
    NewRabbit = 'nR'
    NegotiateFlags = 'nf'
    Pause = 'pa'
    PlayerInfo = 'pb'
    PlayerUpdate = 'pu'
    PlayerUpdateSmall = 'ps'
    QueryGame = 'qg'
    QueryPlayers = 'qp'
    Reject = 'rj'
    RemovePlayer = 'rp'
    ReplayReset = 'rr'
    ShotBegin = 'sb'
    Score = 'sc'
    ScoreOver = 'so'
    ShotEnd = 'se'
    SuperKill = 'sk'
    SetVar = 'sv'
    TimeUpdate = 'to'
    Teleport = 'tp'
    TransferFlag = 'tf'
    TeamUpdate = 'tu'
    WantWHash = 'wh'
    WantSettings = 'ws'
    PortalAdd = 'Pa'
    PortalRemove = 'Pr'
    PortalUpdate = 'Pu'

    @staticmethod
    def code_from_chars(code: str) -> int:
        return int.from_bytes(str.encode(code), byteorder='big')
